networks:
  mynetwork:
    driver: bridge

volumes:
  postgres-data:
    driver: local

services:
  postgres:
    image: postgres:13
    container_name: my_postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=testdb2
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - mynetwork

  app:
    image: jamgadeshivam/java-login:latest
    container_name: java_app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/testdb2
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=123
    networks:
      - mynetwork
    depends_on:
      - postgres

  homepage:
    image: jamgadeshivam/homepage:latest 
    container_name: front_homepage
    ports:
      - "8082:80"
    restart: always 
    networks:
      - mynetwork

